# navbar
menu:
  Home: /
  Archives: /archives/
  Categories: /categories/
  Tags: /tags/
  About: /about/

# site icon
favicon: /favicon.ico

# comments
comments:
  post: true
  about: true

# article directory sidebar
sidebar: true

# Analytics
## Baidu Analytics
baidu_analytics: Your baidu Analytics ID
## Google Analytics
google_analytics: Your Google Analytics ID

# Comments
## Duoshuo
duoshuo_shortname: codehunter
## Disqus
disqus_shortname:

# Social links
social:
  email: dylanzhou0@sina.com
  # stack-overflow:
  # twitter:
  # facebook:
  github: https://github.com/code-hunter
  # weibo: 
  # zhihu: 
  rss: /atom.xml